version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - web_app
